name: wirya_qr_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  firebase_database: ^9.0.7
  uuid: ^3.0.4
  path_provider: ^2.0.11
  google_maps_flutter: ^2.1.1
  flutter_map: ^3.1.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
