name: wirya_qr_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # ✅ Updated Dart SDK for compatibility

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  firebase_core: ^3.12.1  # ✅ Updated Firebase
  firebase_database: ^11.3.4  # ✅ Updated Firebase Database
  uuid: ^4.2.1  # ✅ Latest UUID package
  path_provider: ^2.1.1  # ✅ Updated
  flutter_map: ^8.1.0  # ✅ Use this version
  latlong2: ^0.9.1  # ✅ Updated for compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # ✅ Updated
  flutter_launcher_icons: ^0.9.2  # ✅ Add this package

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/icon.png"  # Path to your app icon
