name: wirya_qr_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  uuid: ^3.0.4
  path_provider: ^2.0.11
  image_gallery_saver: ^1.7.1
  file_picker: ^5.5.0

flutter:
  uses-material-design: true
