// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9Dw_KI62LJmLqoNsjk9HL3tTWZqZXfo',
    appId: '1:786199623818:web:a1154c5892abfb44255573',
    messagingSenderId: '786199623818',
    projectId: 'wirya-qr',
    authDomain: 'wirya-qr.firebaseapp.com',
    databaseURL: 'https://wirya-qr-default-rtdb.firebaseio.com',
    storageBucket: 'wirya-qr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI45YfAjq-G9WALcOvV1nAGnXYj4yR0Hc',
    appId: '1:786199623818:android:1399fd935c2b19a7255573',
    messagingSenderId: '786199623818',
    projectId: 'wirya-qr',
    databaseURL: 'https://wirya-qr-default-rtdb.firebaseio.com',
    storageBucket: 'wirya-qr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPB758vtIToBx6Gt_ZyRLxr-zVyi7bSos',
    appId: '1:786199623818:ios:5328fcf7c9190e68255573',
    messagingSenderId: '786199623818',
    projectId: 'wirya-qr',
    databaseURL: 'https://wirya-qr-default-rtdb.firebaseio.com',
    storageBucket: 'wirya-qr.firebasestorage.app',
    iosBundleId: 'com.example.wiryaQrAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPB758vtIToBx6Gt_ZyRLxr-zVyi7bSos',
    appId: '1:786199623818:ios:5328fcf7c9190e68255573',
    messagingSenderId: '786199623818',
    projectId: 'wirya-qr',
    databaseURL: 'https://wirya-qr-default-rtdb.firebaseio.com',
    storageBucket: 'wirya-qr.firebasestorage.app',
    iosBundleId: 'com.example.wiryaQrAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ9Dw_KI62LJmLqoNsjk9HL3tTWZqZXfo',
    appId: '1:786199623818:web:a036ffef9ac4609d255573',
    messagingSenderId: '786199623818',
    projectId: 'wirya-qr',
    authDomain: 'wirya-qr.firebaseapp.com',
    databaseURL: 'https://wirya-qr-default-rtdb.firebaseio.com',
    storageBucket: 'wirya-qr.firebasestorage.app',
  );
}
